import type { Metadata } from "next";
import "@photo-sphere-viewer/core/index.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body style={{ height: "100vh", width: "100vw", margin: 0}}>
        {children}
      </body>
    </html>
  );
}
